import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsDateString, IsEnum, IsInt, IsOptional, IsPositive, IsString, IsUUID, MaxLength, ValidateIf } from 'class-validator';
import { SyncEventType } from './sync-event-type.enum.js';

export class SyncEventDto {
    @ApiProperty({ enum: SyncEventType, description: 'status_change = the dispatch changed status (send `dispatchStatusId`) · incident = a problem happened during delivery (send `incidentReasonId`)' })
    @IsEnum(SyncEventType)
    type: SyncEventType;

    // UUID v7 (not v4) — generated on-device before the event ever reaches the backend, this is
    // the idempotency key for the whole sync mechanism (RF-U13, Escenario 3).
    @ApiProperty({ example: '01933b6e-7f2a-7c3d-9a1b-2f8e6c4d5a10', description: 'UUID v7 generated by the device when the event happened. It is the idempotency key: sending the same one again never duplicates the event (the answer is `already_processed`)' })
    @IsUUID('7')
    clientEventId: string;

    @ApiProperty({ type: 'integer', example: 42, description: 'ID of the dispatch the event is about' })
    @IsInt()
    @IsPositive()
    dispatchId: number;

    // The device's own UTC clock when the change actually happened — not when it finally synced.
    @ApiProperty({ example: '2026-09-22T14:03:00.000Z', description: 'When it really happened on the device, ISO 8601 in UTC (not when it was synced)' })
    @IsDateString()
    occurredAt: string;

    @ApiPropertyOptional({ type: 'integer', example: 3, description: 'Required when type = status_change: the new dispatch status ID (1 = pending, 2 = in_transit, 3 = delivered, 4 = not_delivered, 5 = returned)' })
    @ValidateIf((o: SyncEventDto) => o.type === SyncEventType.STATUS_CHANGE)
    @IsInt()
    @IsPositive()
    dispatchStatusId?: number;

    @ApiPropertyOptional({ type: 'integer', example: 2, description: 'Required when type = incident: the ID of the incident reason' })
    @ValidateIf((o: SyncEventDto) => o.type === SyncEventType.INCIDENT)
    @IsInt()
    @IsPositive()
    incidentReasonId?: number;

    @ApiPropertyOptional({ maxLength: 1000, example: 'Client not at home', description: 'Optional free text: why the status changed, or a description of the incident' })
    @IsOptional()
    @IsString()
    @MaxLength(1000)
    detail?: string;
}
