import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { IsIn, IsInt, IsOptional, IsPositive, IsString, IsUUID, Max, MaxLength } from 'class-validator';

import { INT4_MAX } from '../../../shared/constants/int4.js';

// Comes from a multipart/form-data body — every field arrives as a string, hence @Type(() => Number).
export class SyncEvidenceDto {
    // Same id the client already generated for the delivery_evidences row itself — the
    // idempotency key IS the record's own PK here (see DeliveryEvidence entity).
    @ApiProperty({ example: '01933b6e-7f2a-7c3d-9a1b-2f8e6c4d5a10', description: 'UUID v7 generated by the device; it becomes the evidence record ID, so resending the same one never duplicates it' })
    @IsUUID('7')
    clientEventId: string;

    @ApiProperty({ type: 'integer', example: 42, description: 'ID of the dispatch this evidence belongs to' })
    @Type(() => Number)
    @IsInt()
    @IsPositive()
    @Max(INT4_MAX)
    dispatchId: number;

    @ApiProperty({ enum: ['photo', 'signature', 'otp'], description: 'Kind of evidence: a photo of the delivery, the recipient signature, or the OTP code they gave' })
    @IsIn(['photo', 'signature', 'otp'])
    type: string;

    @ApiPropertyOptional({ example: '123456', maxLength: 10, description: 'The OTP code the recipient gave. Used when type = otp' })
    @IsOptional()
    @IsString()
    @MaxLength(10)
    otpCode?: string;
}
